[package]
name = "burn-mario-rl"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", default-features = false, features = ["std", "ndarray", "autodiff", "flex"] }
libloading = "0.9.0"

[features]
flex = ["burn/flex"]
tch = ["burn/tch"]
cuda = ["burn/cuda"]
wgpu = ["burn/wgpu"]
